### ISSUE TITLE
Add more integrity checks on fields in JSON schema (ENVO, KEGG terms, etc.)

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-metadata#308] opened 2021-04-01 13:47 UTC
There was an instance where two forms of KEGG id prefixes got into the pilot metadata so we want to guard against things like that in the future.

**Comment by jeffbaumes** [comment] 2021-04-06 13:24
@wdduncan I assigned you and @jbeezley to this one. When ingesting annotations, we need to make sure the schema validates only valid ids (e.g. ENVO, KEGG, etc.) and I believe some regexes on the schema would help here. Could you help us figure out where to add these?

**Comment by wdduncan** [comment] 2021-04-06 13:25
Thanks @jeffbaumes   
Can you post some examples of the bad data?

**Comment by jeffbaumes** [comment] 2021-04-06 13:35
I believe there was an issue where function IDs sometimes came through with prefix `KO:` and sometimes came through with prefix `KEGG_ORTHOLOGY:`. A regex in schema validation could catch things like this. Basically if any ID should match a regex we should put a regex in the schema. @jbeezley may have further thoughts here.

**Comment by dehays** [comment] 2021-04-07 18:01
Didn't see the KEGG case, but this is the same as the ENVO case in #294 - @wdduncan  The request here is to identify fields for which the raw value must conform to a regex and then do that validation.  Looks like JSON Schema can do that ( https://json-schema.org/understanding-json-schema/reference/regular_expressions.html ) but that doesn't mean that the JSON Schema that gets generated in NMDC can include that.  Ideas Bill?

**Comment by ssarrafan** [comment] 2021-04-27 20:23
Moving to May sprint per Bill's request and adding Large size label.  
Comment from Bill:
 I need to investigate how to use regular expressions in jsonschema to validate data. So, I will give an estimate of one week, but the issue is quite open ended. The only use case of KEGG_ORTHOLOGY. I imagine there are other use cases.

**Comment by cmungall** [comment] 2021-04-28 19:55
Sorry just saw this now. I think this should be straightforward. 

There are different levels of checks

 1. Is the ID prefix valid? (e.g. KEGG.KO vs KEGG.ORTHOLOG)
 2. Is the local part of the ID syntactically conformant? (e.g. KEGG:K\d+)
 3. Is the ID valid and appropriate?

The first is very easy to do with using the existing `id_prefixes` annotated in the schema

The second we can do by adding additional regexes

For the 3rd we have two approaches

 1. Additional code outside the schema that does lookups with public APIs to check the ID is valid and not obsolete and yields a semantically appropriate entity
 2. We enumerate all valid IDs and include as an enum in the schema. Note these could be quite large, but we would generate these programmatically and include as a separate import

But we can tackle this incrementally, start with 1 then 2

**Comment by ssarrafan** [comment] 2021-05-27 23:13
@cmungall and @wdduncan what would you like to do with this issue?  Can we close it as the considering is done?  And open a new ticket for June to start implementing per Chris's comment?

**Comment by cmungall** [comment] 2021-05-27 23:50
Let's make one ticket for 1+2, another for 3

**Comment by ssarrafan** [comment] 2021-05-28 00:07
Created two GH issues for June, assigned to @cmungall @wdduncan and @turbomam.  Please remove wrong assignments if any or let me know.  

https://github.com/microbiomedata/nmdc-metadata/issues/360
https://github.com/microbiomedata/nmdc-metadata/issues/362

Closing this issue.

**Closed by ssarrafan** 2021-05-28 00:07 UTC
Labels: LARGE, spring portal-pipeline refactor

**Comment by turbomam** [comment] 2021-06-21 15:59
Hello, all. You may have seen that this was moved to https://github.com/microbiomedata/nmdc-schema/issues/69

@jeffbaumes , I don't think you and I have had much on-on-one conversation. I joined @cmungall's group mid March.

Can someone share some JSON objects that contain some of the error patterns mentioned in this original issue post?

I have reviewed the declared orthology prefixes, and I have added acceptable patterns for the local part of their IDs in 
- https://github.com/microbiomedata/nmdc-schema/blob/issue-62/src/schema/annotation.yaml

which corresponds to 
- https://github.com/microbiomedata/nmdc-schema/pull/70

I can continue to add local portion patterns for other classes in `annotation.yaml` (or even other files) based on those that have `id_prefixes` slots. See 
- https://github.com/microbiomedata/nmdc-schema/blob/issue-69/util/discover_local_pattern/Find%20opportunities%20for%20ID%20validation.ipynb
