### ISSUE TITLE
Define pipeline product metadata

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#80] opened 2020-06-22 20:00 UTC
Shane's draft:

https://docs.google.com/document/d/12a8c6ZDp4fyiRjYYBtJQjkyn7rZyAe_6y7EX7LJYuiM/edit#heading=h.as9kdn9iw81k

Chienchi's example:
https://jsonblob.com/2137bcc9-c165-11ea-bf47-77ac2761baa8

**Comment by cmungall** [comment] 2020-07-07 01:08
In terms of general schema structure, we are thinking of following PROV:

![img](https://www.w3.org/TR/prov-o/diagrams/starting-points.svg)

We have the prov base classes here: https://github.com/microbiomedata/nmdc-metadata/blob/master/schema/prov.yaml

Straw man:

![image](https://user-images.githubusercontent.com/50745/86680601-964e8180-bfb3-11ea-8278-ef59366aea96.png)

TBD: which direction to traverse the json tree? currently we have omics processing, which has a non-imlined list of output objects, each of which has inlined metaadata about workflow execution

**Comment by cmungall** [comment] 2020-07-07 01:14
See https://microbiomedata.github.io/nmdc-metadata/docs/WorkflowExecutionActivity

**Comment by cmungall** [comment] 2020-07-08 19:53
Parking some slides of relevance from @stain here, will provide context later: http://slides.com/soilandreyes/2018-01-15-interoperable-provenance

**Comment by chienchi** [comment] 2020-07-08 22:11
draft json file: 
https://gist.github.com/chienchi/8bf29a5501b479d332bbd44cd240821f

**Comment by wdduncan** [comment] 2020-07-09 00:55
Do want to have an inverse relation to has_input. The biosample data has associated project ids. This makes it easier to model `biosample is_input_to sequencing project` in one pass over the data.

**Comment by wdduncan** [comment] 2020-07-14 18:46
Here is an example for metagenome annotation activity:
```
[
  {
    "id": "", ## need to specify a URI to identify the activity ##
    "name": "", ## If you don't have names in the data, you can just name it 'metagenome annotation activity' ##
    "started_at_time": "2020-06-12", 
    "ended_at_time": "2020-06-12", 
    "was_informed_by": "gold:Gp0095966",
    "type": "annotation activity", ## is this specific enough? is there more than one type of annotation activity? ##
    "has_input": [
      "nmdc:e08985ca1c68cf494875a19802bb535a" # is this a data object?
    ], 
    "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1", 
    "has_output": [
      "nmdc:d184ae225006c3cf9282775289aa0c06", 
      "nmdc:bfcf65ba9992cd019c6e88427efac84c", 
      "nmdc:071da0907650de9024c225da758d2f16", 
      "nmdc:749ff7a21de61359f78c52648b472539"
    ], 
    "metadata": {}, 
    "workflow_version": "0.1.0", 
    "execution_resource": "NERSC - Cori"
  },
  {
    ... second annotation activity
  },
  ... etc.
]
```

**Comment by wdduncan** [comment] 2020-07-14 19:09
Does the git_url also imply that the workflow version is 0.1.0? If so, the workflow version is redundant info. Also, need to decide on "metadata" element.

**Comment by chienchi** [comment] 2020-07-14 19:45
Thanks for the example.  Follow this example, I did the read QC.
```json
{
    "ReadQC": {
        "id": "",
        "name": "ReadQC activiity 1472_51289",
        "was_informed_by": "gold:Gp0061285",
        "started_at_time": "2020-03-19",
        "ended_at_time": "2020-03-19",
        "type": "ReadQC activity",
        "execution_resource": "NERSC - Cori",
        "git_url": "https://github.com/microbiomedata/ReadsQC/releases/tag/1.0.0",
        "has_input": [
            "jgi:5bd6893146d1e604fecfb2fd"
        ],
        "has_output": [
            "nmdc:6b58ac1c6c086b4bb2c318ace84901e6",
            "nmdc:fa4c5cb8f6d7fb9143fc0d8d802e2c6b"
        ],
        "stats": {
            "input_read_count": 97750956,
            "input_read_bases": 14662643400,
            "output_read_count": 96006306,
            "output_read_bases": 14341531952
        }
    }
}
```

**Comment by wdduncan** [comment] 2020-07-14 19:57
@chienchi Thanks. I would change as follows:
```
[
  {
		"id": "", 
		"name": "ReadQC activiity 1472_51289",
		"was_informed_by": "gold:Gp0061285",
		"started_at_time": "2020-03-19",
		"ended_at_time": "2020-03-19",
		"type": "readQC activity",
		"execution_resource": "NERSC - Cori",
		"git_url": "https://github.com/microbiomedata/ReadsQC/releases/tag/1.0.0",
		"has_input": [
				"jgi:5bd6893146d1e604fecfb2fd"
		],
		"has_output": [
				"nmdc:6b58ac1c6c086b4bb2c318ace84901e6",
				"nmdc:fa4c5cb8f6d7fb9143fc0d8d802e2c6b"
		],
		"input_read_count": 97750956,
		"input_read_bases": 14662643400,
		"output_read_count": 96006306,
		"output_read_bases": 14341531952
  },
  { ... next read QC activity ...},
  ... etc.
]
```
We still need to define a URI scheme for the IDs.

**Comment by jeffbaumes** [comment] 2020-07-14 20:01
This concrete example is looking good, and we've confirmed that the `was_informed_by` property links into an omics processing identifier we have in an earlier data dump so this would potentially be able to be linked into the DB and UI. We do not seem to have the data objects referenced in the `has_input` and `has_output` fields, but I'm less concerned about getting all of those (we could stub out dummy data objects for the time being if needed).

**Comment by chienchi** [comment] 2020-07-14 20:15
> We still need to define a URI scheme for the IDs.

Got it. For the output data object, currently Shane and I used md5 for the object id. Here is the corresponding output from the previous read analysis activity json file. 
```json
[
    {
        "id": "nmdc:6b58ac1c6c086b4bb2c318ace84901e6",
        "name": "filterStats.txt",
        "description": "Filtered read data stats for gold:Gp0061285",
        "file_size_bytes": 289,
        "type": "nmdc:DataObject"
    },
    {
        "id": "nmdc:fa4c5cb8f6d7fb9143fc0d8d802e2c6b",
        "name": "12718.2.279671.TGGATCAC-GTGATCCA.fastq.gz",
        "description": "Filtered read data for gold:Gp0061285",
        "file_size_bytes": 7230036234,
        "type": "nmdc:DataObject"
    }
]
```

**Comment by dehays** [comment] 2020-07-14 20:27
@jeffbaumes @chienchi  Shane and Chien-Chi will be producing new DataObject JSON objects for the outputs as Chien-Chi has shown above.  I think using the md5 as IDs on the new file objects is fine. Jeff - you don't have JSON for these new DataObjects yet.

There is an issue we need to address in linking to the existing raw fastq DataObjects.  I had thought those were also using md5 hash values as IDs but I learned that they are not (They are 24 hex character mongo IDs.). That difference is why Jeff is not finding them by ID among the DataObject JSON that was previously generated.  My suggestion is to regenerate those DataObjects to use md5 hash values as IDs so that everything representing a file is currently an md5

**Comment by chienchi** [comment] 2020-07-15 16:16
For Annotation:
https://portal.nersc.gov/project/m3408/meta/data_objects.json
https://portal.nersc.gov/project/m3408/meta/mg_annotation_objects.json
For readQC:
https://portal.nersc.gov/project/m3408/meta/readQC_activity_data_objects.json
https://portal.nersc.gov/project/m3408/meta/readQC_activity.json
For Assembly:
https://portal.nersc.gov/project/m3408/meta/metagenomeAssembly_activity.json
https://portal.nersc.gov/project/m3408/meta/metagenomeAssembly_data_objects.json

The sync meeting yesterday is very helpful. Please take a look for the current json files Shane and I have for the three workflow activities.

**Comment by wdduncan** [comment] 2020-07-15 18:04
The format of the **data object** files seems fine:
- https://portal.nersc.gov/project/m3408/meta/data_objects.json
- https://portal.nersc.gov/project/m3408/meta/readQC_activity_data_objects.json
https://portal.nersc.gov/project/m3408/meta/metagenomeAssembly_data_objects.json

**Comment by wdduncan** [comment] 2020-07-15 18:22
@chienchi  are all the data objects "https://portal.nersc.gov/project/m3408/meta/data_objects.json" associated with a particular kind of workflow activity?   

E.g., readQC_activity_data_objects.json is associated with a readQC activity and metagenomeAssembly_data_objects.json is associated with metagenome assembly activity.

**Comment by chienchi** [comment] 2020-07-15 19:09
Yes.  The data_objects.json should associated with annotation workflow.

**Comment by wdduncan** [comment] 2020-07-15 19:45
@chienchi Thanks!

**Comment by anubhav0fnu** [comment] 2020-07-16 02:35
@wdduncan , @cmungall , @dehays , @dehays , @jeffbaumes, @chienchi 
Here is a sample JSON object for the meta-proteomics pipeline:
https://jsonblob.com/400362ef-c70c-11ea-bf3d-05dfba40675b
Please provide your suggestions.

**Comment by dehays** [comment] 2020-07-16 09:05
@anubhav0fnu 
I looked at this: [https://jsonblob.com/400362ef-c70c-11ea-bf3d-05dfba40675b](url) and this: [https://github.com/microbiomedata/metaPro/blob/master/docs/index.rst](url)

and compared with metagenomeAssembly_activity.json and Bill’s comment with examples 5 comments above in this thread.


First, both the mmdc:OmicsProcessing object and the mmdc:DataObject that represents its file output already exist.  These were created by Bill in February based on the instrument run metadata that EMSL provided.

You can look at the full set of JSON at [https://github.com/microbiomedata/nmdc-metadata/blob/master/metadata-translation/notebooks/output/test-pipeline.zip](url)

This is what they look like: 

```
   {
      "id": "emsl:404590",
      "name": "FECB_21_5093B_01_23Dec14_Tiger_14-11-12",
      "description": "High res MS with low res CID MSn",
      "part_of": [
        "gold:Gs0110132"
      ],
      "has_output": [
        "emsl:output_404590"
      ],
      "type": "nmdc:OmicsProcessing"
    }

   {
      "id": "emsl:output_404590",
      "name": "output: FECB_21_5093B_01_23Dec14_Tiger_14-11-12",
      "description": "High res MS with low res CID MSn",
      "file_size_bytes": 503296678,
      "type": "nmdc:DataObject"
    }
```

 You do not need to go find each of these, I just include them to point out that both their ID values are based on the EMSL dataset ID.  This means that for the mmdc:metaPro object you create you can figure out the was_informed_by property ID (ID of the nmdcOmicsProcessing object above) and the MSMS output file DataObject ID (the nmdc:DataObject above).

So for your example, the was_informed_by property would be:

`"was_informed_by": "emsl:404590", `

The analysis execution objects you create will not be referencing sequencing projects (like "gold:Gp0095970”) they will be referencing MSMS runs like "emsl:404590"

Your first input is the output of the MSMS run and Bill created IDs for those by prefixing the EMSL dataset ID with “output_” so as you see above, the ID of that nmdc:DataObject is "emsl:output_404590"
Your other input is the DataObject that represents the faa file produced by metagenome annotation.  Shane produced the JSON for that DataObject because it is the output of a mmdc:MetagenomeAnnotation workflow activity.  Because Shane is using md5 for the IDs of mmdc:DataObject objects, you should not need to hunt that one down either.  It’s ID should be “nmdc:be112c8aeccd5d730d802a60eb63cf75” as long as you are both referring to the same faa file (which you should be). 

I don’t know that you need to include new nmdc:DataObject objects for the parameter file, the msgfplus and the contaminant file as inputs.  Do these change with each execution of Paul’s workflow?  Are these something a researcher coming to NMDC would want to download?

Without those - your has_input list (Per Bill’s comments, the property is “has_input” and NOT “has_inputs”.  Same deal for “has_output” and not “has_outputs”) would look like this:

```
"has_input": [
			"emsl:output_404590”,
                 “nmdc:be112c8aeccd5d730d802a60eb63cf75”
		], 
```

You will need to create nmdc:DataObject JSON for each of your outputs.  They should not be embedded in your nmdc:metaPro object.  Following Shane’s md5 ID scheme makes it easy to know their IDs so your has_output list would look like:

```
"has_output": [
			"nmdc:e0c70280a7a23c7c5cc1e589f72e896e", 
			"nmdc:73c390c95a2337925b9bedd89f94d0e7"
		]
```


You have some other empty stuff in your outputs section in your example but I just see the two files referenced above.  The two nmdc:DataObject objects you’d need would then be:

```
{
      "id": "nmdc:e0c70280a7a23c7c5cc1e589f72e896e",
      "name": "404590_resultant.tsv",
      "description": “resultant file“,
      "file_size_bytes": "10948480",
      "type": "nmdc:DataObject"
    },

{
      "id": "nmdc:73c390c95a2337925b9bedd89f94d0e7",
      "name": "404590_data_out_table.tsv",
      "description": “data out table“,
      "file_size_bytes": 20581,
      "type": "nmdc:DataObject"
    }
```

Put the list of these nmdc:DataObject objects in another file for Bill with a name like emsl_analysis_data_objects.json.

Other comments

We do not charge by the character when naming your class.  Might I suggest “nmdc:MetaProteomicAnalysis” rather than “nmdc:metaPro”?  (Bill is asking that we name classes starting with a capital too.)

Not so sure about your scheme for the name property that results in "Metagenome:1393_65601:1045042”.  I see you are building that from the JGI proposal ID, sample ID and sequencing project ID. Maybe talk to Shane and/or Paul about naming for the metaproteomic analysis workflow instances.

The dataset_id and dataset_name properties you have are of the input dataset.  Seems those might be redundant with what is in the input DataObject.

Here’s what I end up with for JSON: [https://jsonblob.com/991cd7ec-c740-11ea-bf3d-a56db33087e2](url)

**Comment by wdduncan** [comment] 2020-07-16 23:25
I've added @scanon and @chienchi data:

annotation files:   
metagenome_annotation_activities.json   
metagenome_annotation_data_objects.json  

assembly files:   
metagenome_assembly_activities.json   
metagenome_assembly_data_objects.json  

readQC files:  
readQC_activities.json  
readQC_data_objects.json

Files are located in the [data/aim-2-workflows](https://github.com/microbiomedata/nmdc-metadata/tree/master/metadata-translation/src/data/aim-2-workflows) directory.  

@anubhav0fnu let me know when you ready :)

**Comment by anubhav0fnu** [comment] 2020-07-17 09:39
@wdduncan , @dehays 
Files are here `/global/cfs/cdirs/m3408/www/meta/MetaProteomicAnalysis/  `
```
.
|-- [Jul 17  2:38]  hessMetaProteomicAnalysis_activity.json
|-- [Jul 17  2:38]  hessemsl_analysis_data_objects.json
|-- [Jul 17  1:16]  stegenMetaProteomicAnalysis_activity.json
`-- [Jul 17  1:16]  stegenemsl_analysis_data_objects.json
```

**Comment by wdduncan** [comment] 2020-07-17 15:09
Can you change the permissions for the files so that I can access them without having to log in. 

E.g., make https://portal.nersc.gov/project/m3408/meta/MetaProteomicAnalysis/hessMetaProteomicAnalysis_activity.json public.

**Comment by wdduncan** [comment] 2020-07-17 15:28
Where there any "stats" you wanted to add for the nmdc:MetaProteomicAnalysis files?:

https://portal.nersc.gov/project/m3408/meta/MetaProteomicAnalysis/hessMetaProteomicAnalysis_activity.json  
https://portal.nersc.gov/project/m3408/meta/MetaProteomicAnalysis/stegenMetaProteomicAnalysis_activity.json

The data object files seem fine:
https://portal.nersc.gov/project/m3408/meta/MetaProteomicAnalysis/hessemsl_analysis_data_objects.json   
https://portal.nersc.gov/project/m3408/meta/MetaProteomicAnalysis/stegenemsl_analysis_data_objects.json

**Comment by jbeezley** [comment] 2020-07-17 15:30
> I've added @scanon and @chienchi data:
> 
> annotation files:
> metagenome_annotation_activities.json
> metagenome_annotation_data_objects.json
> 
> assembly files:
> metagenome_assembly_activities.json
> metagenome_assembly_data_objects.json
> 
> readQC files:
> readQC_activities.json
> readQC_data_objects.json
> 
> Files are located in the [data/aim-2-workflows](https://github.com/microbiomedata/nmdc-metadata/tree/master/metadata-translation/src/data/aim-2-workflows?rgh-link-date=2020-07-16T23%3A25%3A07Z) directory.

I realize you may not be finished yet, but I tried using these files and found a couple of issues.

There are missing data objects:
```
nmdc:7977dbf7c5e883dec263fe8f23922313
nmdc:8d23c95a2ec52192478379e558bed026
nmdc:9e529a9d01aec09f0401e806e71bfa2a
nmdc:56a10842285cfe56534eeaf60fa829bf
```
and a few duplicates in the activities:
```
metagenome_annotation nmdc:5f7db4508abbc9b240e0ef7697484eea
reads_qc nmdc:d8aef565dc0a18a0a17ebeb77a3a7153
reads_qc nmdc:f289238604e30ce43a735d47f027e086
```

**Comment by dehays** [comment] 2020-07-17 15:44
@jbeezley Thanks Jon - we will investigate why there are references to missing data objects before giving you JSON today. We are looking at the metaproteomicsAnalysis json now.

**Comment by chienchi** [comment] 2020-07-17 15:47
@jbeezley Thanks.  Those are missing data objects are from reads_qc. I will fix that and the duplicate reads_qc.

**Comment by wdduncan** [comment] 2020-07-17 19:41
Hess & Stegen metaprotemics data has been merged. See PR https://github.com/microbiomedata/nmdc-metadata/pull/122

**Comment by wdduncan** [comment] 2020-07-21 01:10
I think we are good for now. Closing this ticket.

**Closed by wdduncan** 2020-07-21 01:10 UTC
