### ISSUE TITLE
Change set of EMSL datasets used in NMDC (was 'Portal metabolomics results not displaying Eoin Brodie's study')

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#341] opened 2021-05-07 18:32 UTC
@dehays and I were looking at the portal and noticed that there is a problem with displaying metabolomics samples when searching on Eoin Brodie's study.  See attached screenshot.  

<img width="1340" alt="Screen Shot 2021-05-07 at 11 16 27 AM" src="https://user-images.githubusercontent.com/79225425/117493435-d5c56180-af27-11eb-8ba7-1bc9304ae653.png">

**Comment by pvangay** [comment] 2021-05-11 14:33
FYI this looks like a duplicate of https://github.com/microbiomedata/nmdc-server/issues/333

**Comment by dehays** [comment] 2021-05-20 22:16
The solution to this and other issues of omics_processing without has_input samples is to use an agreed upon (Yuri, Lee Ann) set of instrument process datasets from EMSL as the basis of inclusion in NMDC.

What we currently have in NMDC is based on these files that Lee Ann provided:

[](https://docs.google.com/spreadsheets/d/1VMJ_Tvld3cZYh9NJHdItVWpV0DmOUYH4)
[](https://docs.google.com/spreadsheets/d/1lWp_n8ZUKMjEk1wybs1xlXJj0nAGwxAj)

Yuri indicates that these include many datasets that should NOT have been included and that the datasets listed in these files are correct:

[](https://docs.google.com/spreadsheets/d/1V2f8UYmAQk5UIGfgBxkCVpeNwL7dQSJV)
[](https://docs.google.com/spreadsheets/d/1VUqe_DOCQT7ZPhU565Xf7MtvZbWsT_VD)

At least for Natural Organic Matter and Metabolomics omics types.  All Lipidomics omics type datasets and should be removed.

General validation at the schema level would be to make has_input on omics_processing entities require a non empty value (Cannot be null and cannot be [].)

*Complicating case using the EMSL dataset lists above:  they all include blank and config datasets which should be removed now and then added later once the NMDC schema can represent additional omics_processing input relationships and possibly special sample types for blanks.

**Comment by pvangay** [comment] 2021-07-08 20:49
appears to have been fixed with latest changes

**Closed by pvangay** 2021-07-08 20:49 UTC
Labels: metadata-update
