### ISSUE TITLE
Add support for range values for Depth (Brodie dataset)

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-metadata#355] opened 2021-05-26 21:33 UTC
Discovered this when @mslarae13 and I sat down with Eoin and his team to review their data in the portal.

_Soil microbial communities from the East River watershed near Crested Butte, Colorado, United States - ER_DNA_380_ has a depth of 5, when it should be 5-15 ([Brodie spreadsheet](https://drive.google.com/file/d/19PH8F-YqTZ3oUoWg1vKtPKHZT9YznXoA/view)). All of the depth values for the Brodie dataset were submitted as a range - it is common to report depth as a range for Soil and Sediment environments.

Unclear if this requires a schema update, or if the metadata value was incorrectly stored, or simply not being displayed properly on the UI. Please relabel/reassign as needed @dehays

**Comment by dehays** [comment] 2021-05-26 21:59
This is a larger problem because MIxS has only a single value for 'depth' and does not support ranges.  If NMDC tries to support a range than that would mean diverging from MIxS. (There is a reason that Darwin Core has two fields: minDepth and maxDepth.)

**Comment by pvangay** [comment] 2021-05-26 22:03
Not sure if this is helpful, but MIxS's description for Depth:

> Depth is defined as the vertical distance below local surface, e.g. For sediment or soil samples depth is measured from sediment or soil surface, respectively. Depth can be reported as an interval for subsurface samples.

**Comment by mslarae13** [comment] 2021-06-10 00:24
https://github.com/microbiomedata/nmdc-metadata/issues/327#issuecomment-857219621

comment from Reddy. range is ok for GOLD.

**Comment by pvangay** [comment] 2021-06-10 23:00
Can we modify the schema to support ranges for Depth? We discussed this at yesterday's metadata sync and I believe the decision was to support it. Please confirm @dehays @cmungall @wdduncan

**Comment by wdduncan** [comment] 2021-06-15 15:29
I have filed a ticket with GSC to assess needs for measurements:  
https://github.com/GenomicsStandardsConsortium/mixs/issues/166

**Comment by wdduncan** [comment] 2021-07-16 16:04
Related to issue https://github.com/microbiomedata/nmdc-schema/issues/80

**Comment by ssarrafan** [comment] 2021-07-23 23:43
Closing this issue since it's a duplicate of microbiomedata/nmdc-schema#80. Checked with @wdduncan.

**Closed by ssarrafan** 2021-07-23 23:43 UTC
Labels: metadata-update
