### ISSUE TITLE
add attributes to study model

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#301] opened 2021-03-22 17:39 UTC
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/ingest/study_additional.json

A number of study related fields are displayed in the portal UI that are not currently in the schema.  In addition to deciding what must be added, we need to consider the process by which these values are included

**Comment by dehays** [comment] 2021-03-31 18:23
To clarify - this issue is about the attributes getting added (PI web sites, publications, PI image) downstream in the portal UI.  Issue #150 is about adding a relationship between biosamples and studies

**Comment by dwinston** [comment] 2021-04-01 15:54
connects to e.g. #314

**Comment by dwinston** [comment] 2021-04-01 15:57
@jeffbaumes duplicated by #315?

**Comment by jeffbaumes** [comment] 2021-04-06 13:56
I believe a conversation about what is in this JSON between @jbeezley and @wdduncan could start to address this.

**Comment by wdduncan** [comment] 2021-04-16 19:21
@ssarrafan can you move this to the next sprint?

**Comment by ssarrafan** [comment] 2021-04-16 21:18
> @ssarrafan can you move this to the next sprint?

It's been moved to the May sprint.

**Comment by kfagnan** [comment] 2021-05-05 23:46
Was the suggestion at today's TechSync to divide this ticket up?

It would be nice if there were default values or placeholders for fields that we know we want to show up on the portal - even if we don't have the data. The route in for the data definitely needs to be sorted out - as David pointed out. 

It would also be nice to give the users a way to upload this content, but that can be down the road.

**Comment by ssarrafan** [comment] 2021-06-02 23:23
Removing Jon and Donny per discussion with Kjiersten.  @wdduncan let me know if this shouldn't be assigned to you or if you don't have time to work on it.

**Comment by ssarrafan** [comment] 2021-06-11 03:36
@wdduncan is this ticket a duplicate of #51 ? Can this one be closed?

**Comment by wdduncan** [comment] 2021-06-11 17:59
Hi @ssarrafan  This looks like a duplicate of https://github.com/microbiomedata/nmdc-schema/issues/51.
So, I'll close this ticket. Reopen if needed.

**Closed by wdduncan** 2021-06-11 17:59 UTC
Labels: enhancement, spring portal-pipeline refactor
